# https://arayinfosolutions.com/
# This is the ros2 carla9.14 integration.
# Related files can be found under our aray-ai github repository.
# https://github.com/aray-ai/carla-0.9.14


# This docker compose file contains..
# 1. Carla 9.14 compiled in python 3.10 environment.
# 2. ROS2 humble
# 3. Carla ROS bridge
# 4. carla client container using python 3.10 environment.

services:

  carla:
    image: carlasim/carla:0.9.14
    container_name: carla_server
    # Sets shared memory to 8GB
    shm_size: 8g 
    ports:
      - 2000-2002:2000-2002
    command: /bin/bash -c "./CarlaUE4.sh -nosound -RenderOffscreen"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 
      - SDL_VIDEODRIVER=x11
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host"
    
    
  # Carla ROS bridge container
  ros-bridge:
    build:
      context: ./ros_carla_bridge/
      dockerfile: Dockerfile
    container_name: ros_bridge
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # connecting with carla network host
      - CARLA_HOST=172.17.0.1
      - CARLA_PORT=2000
#    command: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py host:=172.17.0.1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config/objects.json:/root/config/objects.json
      - ./config/carla_ros.rviz:/root/config/carla_ros.rviz
    tty: true
    stdin_open: true
    runtime: nvidia
    restart: always
    depends_on: 
      carla:
        condition: service_started            
    networks:
      - carla-ros-914_default
         
        
  # Custom ROS2 container using ROS2 Humble
  ros2_container:
    build:
      context: ./ros2-container/
      dockerfile: Dockerfile
    container_name: ros2_container
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - CARLA_HOST=172.17.0.1
      - CARLA_PORT=2000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
   # optional, if using modern desktop environments
      - /run/user/1000:/run/user/1000
    command: >
      bash -c "mkdir -p /tmp/runtime-root &&
               sleep 10 &&
               ros2 run carla_manual_control carla_manual_control"
    depends_on:
      ros-bridge:
        condition: service_started
    networks:
      - carla-ros-914_default



  # Custom Carla Node
#  carla_client:
#    build:
#      context: ./carla_client_node/
#      dockerfile: Dockerfile
#    container_name: carla_client
#    environment:
#      # connecting with carla network host
#      - CARLA_HOST=172.17.0.1
#      - CARLA_PORT=2000
#    restart: always
#    depends_on: 
#      carla:
#        condition: service_started
#      ros-bridge:
#        condition: service_started
#    networks:
#      - carla-ros-914_default

  # foxglove 

  foxglove:
#    image: ghcr.io/foxglove/studio:latest
    image: ghcr.io/jpc/studio:latest
    ports:
      - 8080:8080
    container_name: foxglove_studio
    restart: always
    environment:
      # connecting with carla network host
      - CARLA_HOST=172.17.0.1
      - CARLA_PORT=2000
    networks:
      - carla-ros-914_default


  # foxglove to visualize live data 
  foxglove_bridge:
    build:
      context: ./foxglove_bridge/
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    container_name: foxglove_bridge
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # connecting with carla network host
      - CARLA_HOST=172.17.0.1
      - CARLA_PORT=2000
    command: ros2 launch /launch/foxglove_bridge_launch.xml port:=8765
    restart: always
    depends_on: 
      ros-bridge:
        condition: service_started
    networks:
      - carla-ros-914_default


# The default ntwork used

networks:
  carla-ros-914_default:

  # Example ros talker node
#  ros_talker:
#    image: osrf/ros:humble-desktop-full
#    environment:
#      # connecting with carla network host
#      - CARLA_HOST=172.17.0.1
#      - CARLA_PORT=2000
#    command: ros2 run demo_nodes_cpp talker

   # Example ros listener node
#  ros_listener:
#    image: osrf/ros:humble-desktop-full
#    command: ros2 run demo_nodes_cpp listener
#    depends_on:
#      - ros_talker
#    networks:
#      - carla-ros-914_default
