# https://arayinfosolutions.com/
# This is the ros2 carla9.14 integration.
# Related files can be found under our aray-ai github repository.
# https://github.com/aray-ai/carla-0.9.14

# ROS2 Humble is used for the ros carla bridge.

FROM  osrf/ros:humble-desktop AS base

RUN apt update && apt install -y ros-humble-foxglove-bridge
